# Generated by Django 3.1.5 on 2021-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('speed', models.IntegerField()),
                ('date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
