# Generated by Django 3.1.5 on 2021-01-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='name',
        ),
    ]
