# Generated by Django 3.1.5 on 2021-01-28 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0002_remove_record_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
    ]
