# Generated by Django 3.1.5 on 2021-01-28 07:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('typer', '0003_remove_record_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 7, 13, 26, 535425, tzinfo=utc), verbose_name='date published'),
            preserve_default=False,
        ),
    ]
